// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1L6wNqkKbfi44kGZLlHmjEi1z34zhs_E',
    appId: '1:643236240179:web:5408634fdf17b237a27c46',
    messagingSenderId: '643236240179',
    projectId: 'tulips-eb05a',
    authDomain: 'tulips-eb05a.firebaseapp.com',
    storageBucket: 'tulips-eb05a.appspot.com',
    measurementId: 'G-EYR03PSEN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCm2HbJfPJIcf9gtUEf1whfvcO7z4WRVM',
    appId: '1:643236240179:android:47ae98e06a2a78aba27c46',
    messagingSenderId: '643236240179',
    projectId: 'tulips-eb05a',
    storageBucket: 'tulips-eb05a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhTEBDHLeyiS1oz3Zp0OXpYMBL9Upw70k',
    appId: '1:643236240179:ios:a615191568b23fd4a27c46',
    messagingSenderId: '643236240179',
    projectId: 'tulips-eb05a',
    storageBucket: 'tulips-eb05a.appspot.com',
    iosBundleId: 'com.zoople.tulipsadminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1L6wNqkKbfi44kGZLlHmjEi1z34zhs_E',
    appId: '1:643236240179:web:dae3b1c527bc14f4a27c46',
    messagingSenderId: '643236240179',
    projectId: 'tulips-eb05a',
    authDomain: 'tulips-eb05a.firebaseapp.com',
    storageBucket: 'tulips-eb05a.appspot.com',
    measurementId: 'G-BSQRWB14TT',
  );
}
